In [37]:
import pandas as pd
import numpy as np
import math
import datetime as dt

In [38]:
aapl = pd.read_csv("./data/AAPL.csv", index_col="Date", parse_dates=True, usecols=["Date", "Adj Close"], na_values=["nan"])
ibm = pd.read_csv("./data/IBM.csv", index_col="Date", parse_dates=True, usecols=["Date", "Adj Close"], na_values=["nan"])
jpm = pd.read_csv("./data/JPM.csv", index_col="Date", parse_dates=True, usecols=["Date", "Adj Close"], na_values=["nan"])
spy = pd.read_csv("./data/SPY.csv", index_col="Date", parse_dates=True, usecols=["Date", "Adj Close"], na_values=["nan"])
aapl = aapl.rename(columns={"Adj Close": "AAPL"})
ibm = ibm.rename(columns={"Adj Close": "IBM"})
jpm = jpm.rename(columns={"Adj Close": "JPM"})
spy = spy.rename(columns={"Adj Close": "SPY"})
prices = pd.concat([aapl, ibm, jpm, spy], axis=1)
prices.dropna(subset=["SPY"], inplace=True)
prices

              AAPL     IBM    JPM     SPY
Date
2012-09-12  669.79  203.77  39.92  144.39
2012-09-11  660.59  203.27  39.60  143.91
2012-09-10  662.74  200.95  38.76  143.51
2012-09-07  680.44  199.50  39.30  144.33
2012-09-06  676.27  199.10  38.69  143.77
...            ...     ...    ...     ...
2000-02-07   28.39   97.83  37.37  114.65
2000-02-04   26.88   99.12  37.17  114.82
2000-02-03   25.72  100.40  37.82  115.30
2000-02-02   24.60   97.30  37.45  113.58
2000-02-01   24.96   94.30  38.08  113.49

[3175 rows x 4 columns]

In [39]:
# calc sma-14 for entire date range

# clear out df 
sma = pd.DataFrame(0,index=prices.index, columns=prices.columns)
sma

            AAPL  IBM  JPM  SPY
Date
2012-09-12     0    0    0    0
2012-09-11     0    0    0    0
2012-09-10     0    0    0    0
2012-09-07     0    0    0    0
2012-09-06     0    0    0    0
...          ...  ...  ...  ...
2000-02-07     0    0    0    0
2000-02-04     0    0    0    0
2000-02-03     0    0    0    0
2000-02-02     0    0    0    0
2000-02-01     0    0    0    0

[3175 rows x 4 columns]

In [50]:
#loop over all days
lookback = 14
for day in range(prices.shape[0]):

    # set to na if day too early for SMA
    if day < lookback:
        sma.iloc[day] = np.nan
        # sma[sma.isna().any(axis=1)] result in 14 rows
    else:

        for prev_day in range(day-lookback+1, day+1):
            for sym in range(4):
                sma.iloc[day,sym] = sma.iloc[day,sym] + prices.iloc[prev_day, sym]
        #     sma.iloc[day] = sma.iloc[day] + prices.iloc[prev_day]
        # sma.iloc[day] = prices.iloc[day-lookback+1 : day+1].sum()
        sma.iloc[day] = sma.iloc[day] / lookback

In [51]:
sma

                 AAPL         IBM        JPM         SPY
Date
2012-09-12        NaN         NaN        NaN         NaN
2012-09-11        NaN         NaN        NaN         NaN
2012-09-10        NaN         NaN        NaN         NaN
2012-09-07        NaN         NaN        NaN         NaN
2012-09-06        NaN         NaN        NaN         NaN
...               ...         ...        ...         ...
2000-02-07  30.518874  105.656866  38.981942  112.154311
2000-02-04  30.473506  106.152070  39.188021  112.689887
2000-02-03  30.245897  106.580375  39.439468  113.231924
2000-02-02  29.912172  106.885649  39.614020  113.491815
2000-02-01  29.653036  106.811829  39.841629  113.837139

[3175 rows x 4 columns]

In [ ]:
prices_diff = prices.diff()
prices_diff.iloc[-1] = 0
df_holdings = pd.DataFrame(index=df_holdings, )
df_holdings[price_diff < 0] = -1000
df_holdings[price_diff > 0] = 1000
df_trades = df_holdings.diff()
df_trades.iloc[0] = df_holdings.iloc[0]
impact_count = df_trades.abs()
commission_count = [impact_count > 0] = 1
commission_count

In [53]:
aapl

              AAPL
Date
2012-09-12  669.79
2012-09-11  660.59
2012-09-10  662.74
2012-09-07  680.44
2012-09-06  676.27
...            ...
2000-02-07   28.39
2000-02-04   26.88
2000-02-03   25.72
2000-02-02   24.60
2000-02-01   24.96

[3175 rows x 1 columns]

In [56]:
aaplr = aapl.rolling(window=3)
aaplr

Rolling [window=3,center=False,axis=0,method=single]